### ISSUE TITLE
No handlers could be found for logger

### ISSUE THREAD

**Issue by eemapel** [privazio/pyone#2]
Installed using pip today. Getting following error:

marketpool = one.marketpool.info()
=>
No handlers could be found for logger "pyxb.binding.basis"

**Comment by rvalle** [comment]
Hi!
Can you provide me with information about your python environment? 
I have never seen this error. My first guess is a dependency issue.

I will try to reproduce the error in a python virtual environment, and then fix it.

**Comment by eemapel** [comment]
This is Ubuntu 16.04 VM

# python --version
Python 2.7.12

# pip freeze
ansible==2.4.2.0
asn1crypto==0.23.0
bcrypt==3.1.4
cffi==1.11.2
cryptography==2.1.4
dicttoxml==1.7.4
enum34==1.1.6
idna==2.6
ipaddress==1.0.18
Jinja2==2.10
MarkupSafe==1.0
netaddr==0.7.18
oca==4.10.0
paramiko==2.4.0
pyasn1==0.4.2
pycparser==2.18
PyNaCl==1.2.1
pyone==1.0.1
PyXB==1.2.6
PyYAML==3.12
six==1.11.0

I see PyXB installed though.. Maybe this is related to one of these:
https://sourceforge.net/p/pyxb/discussion/956708/thread/b9375440/
https://lists.fedoraproject.org/pipermail/java-sig-commits/2014-October/023070.html

**Comment by rvalle** [comment]
Thanks! I can now reproduce your problem.

**Comment by rvalle** [comment]
Yes, one of the links your provided had the fix.
I pushed release 1.0.2.
