### ISSUE TITLE
Accessing the content of an object - eg vn

### ISSUE THREAD

**Issue by mmeroberts** [privazio/pyone#4]
Hi,
  I realise that this is probably a simple question, but I am struggling to get values out of the return from say creating a network.  I would like to get the contents of the TEMPLATE in a format that is either a string or a python dict.  The issue is that I only see the pyxb properties when inspecting and I am not sure how to access the contents properly.

I would be really good if you examples covered this

Thanks - I realise this is a newbie question

Martin

**Comment by rvalle** [comment]
note that this repository has moved, 
I have copied your issue to: https://github.com/OpenNebula/addon-pyone/issues/3
lets discuss it there.
